allow-branch = ['main']
sign-commit = true
sign-tag = true
tag-message = "system_proxy.rs {{version}}"
pre-release-commit-message = "Release {{version}}"

pre-release-replacements = [
    # Update the changelog
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] – {{date}}", exactly = 1 },
    { file = "CHANGELOG.md", search = "HEAD", replace = "{{tag_name}}", exactly = 1 },
    { file = "CHANGELOG.md", search = "\\[Unreleased\\]: ", replace = "[Unreleased]: https://github.com/swsnr/system_proxy.rs/compare/{{tag_name}}...HEAD\n[{{version}}]: ", exactly = 1 },
]
