name: CI

on: [push, pull_request]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: EmbarkStudios/cargo-deny-action@v1

  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        rust:
          # Our minimal supported version
          - '1.66.0'
          # The standard Rust version
          - stable
        include:
          - os: ubuntu-22.04
            cargoflags: "--all-features"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: cargo build --all-targets ${{matrix.cargoflags}}
      - run: cargo test
      - if: matrix.rust == 'stable'
        run: cargo clippy --all-targets ${{matrix.cargoflags}}
      # Build docs on Linux only, where we have all features available.
      - run: cargo doc ${{matrix.cargoflags}}
        if: matrix.os != 'windows-latest'
